### ISSUE TITLE
pwn2's has some problems?

### ISSUE THREAD

**Issue by AI0day** [Hcamael/docker_lib#1]
Sending build context to Docker daemon 891.4 kB
Step 1 : FROM registry.cn-beijing.aliyuncs.com/hcamael/ubuntu:base
Pulling repository registry.cn-beijing.aliyuncs.com/hcamael/ubuntu
Error: image hcamael/ubuntu:base not found

**Comment by Hcamael** [comment]
Sorry. 
registry.cn-beijing.aliyuncs.com/hcamael/ubuntu:base       是我私有仓库

把这个改成ubuntu:16.04
就OK了
