### ISSUE TITLE
I have a question！

### ISSUE THREAD

**Issue by AI0day** [Hcamael/docker_lib#2]
When I pwn pwn0,I make payload "A" * 40 as payload and the getflag()can be executed.
However,payload is "a"*40,getflag() is successful.

**Comment by Hcamael** [comment]
见http://0x48.pw/2016/11/03/0x26/
或者自己逆向看看, 为啥"a"*40会成功getflag

**Comment by aaeolus** [comment]
pwn0，pwn1是不是开了nx啊，我用gdb的checksec看是开了nx的

**Comment by Hcamael** [comment]
@aaeolus checksec看开了那就是开了
